name: Typescript Check PR

on:
  pull_request: 
    branches:
      - "dev"

jobs: 
  pullrequest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install 
        run: npm install --force

      - name: Check
        run: npm run check

      - name: Lint
        run: npm run lint

